name: CI

on:
  push:
    branches: [ making_hw1 ]
  pull_request:
    branches:
     -making_hw1
     - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install references
        run: sudo apt-get install libgtest-dev -y && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib && sudo apt install build-essential && sudo apt install git && sudo apt-get install -y cppcheck && sudo apt-get install valgrind && sudo apt-get install -y lcov && sudo apt-get install -y gcovr

      - name: build
        run: mkdir build && cd build && cmake .. && make

      - name: static analysis and linters
        run: ./linters/run.sh build/IW_1 build/gtests && cppcheck -q --enable=all --inconclusive --platform=unix64 --suppress=missingIncludeSystem ./src ./include ./gtests

      - name: tests
        run: ./build/gtests 
        
      - name: valgrind
        run: valgrind --tool=memcheck --leak-check=full -s ./build/gtests

      - name: code coverage
        run: gcovr -r .
